image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
  - cmd: dotnet restore

test_script:
  - ps: dotnet test .\KD.FakeDb.XUnitTests\KD.FakeDb.XUnitTests.csproj
  - ps: dotnet test .\KD.FakeDb.XUnitTests.Connection\KD.FakeDb.XUnitTests.Connection.csproj